# Generated by Django 3.1.1 on 2020-10-12 20:10

from django.db import migrations, models
import venda.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animal', '0001_initial'),
        ('cliente', '0001_initial'),
        ('funcionario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_venda', models.DateField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6)),
                ('mostrar', models.BooleanField(default=True)),
                ('animal', models.ForeignKey(on_delete=models.SET(venda.models.Venda.get_sentinel_user), to='animal.animai')),
                ('cliente', models.ForeignKey(on_delete=models.SET(venda.models.Venda.get_sentinel_user), to='cliente.cliente')),
                ('funcionario', models.ForeignKey(on_delete=models.SET(venda.models.Venda.get_sentinel_user), to='funcionario.funcionario')),
            ],
            options={
                'db_table': 'vendas',
            },
        ),
    ]
