# Generated by Django 3.1.1 on 2020-10-12 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', models.CharField(max_length=25)),
                ('sexo', models.CharField(max_length=1)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6)),
                ('mostrar', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'animais',
            },
        ),
    ]
