# Generated by Django 3.1.1 on 2020-10-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=25)),
                ('sobrenome', models.CharField(max_length=25)),
                ('cargo', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=30)),
                ('mostrar', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'funcionarios',
            },
        ),
    ]
